version = 2

disabled_plugins = [
    "io.containerd.snapshotter.v1.devmapper",
    "io.containerd.snapshotter.v1.zfs",
    "io.containerd.snapshotter.v1.devmapper",
    "io.containerd.snapshotter.v1.aufs",
    "io.containerd.tracing.processor.v1.otlp",
    "io.containerd.internal.v1.opt",
    "io.containerd.internal.v1.tracing",
]

[plugins."io.containerd.grpc.v1.cri"]
enable_selinux = true

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
SystemdCgroup = true
